apiVersion: v1
kind: Service
metadata:
  name: hub
spec:
  ports:
  - port: 9810
    targetPort: 9810
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hub
subsets:
- addresses:
  - ip: 192.168.4.31
  ports:
  - port: 9810
